[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "openstream"
version = "1.0.0a0"
description = "Local and LAN SOCKS5 proxy over OpenVPN without routing the whole host through VPN"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name = "Amir-A664" }
]
keywords = ["openvpn", "socks5", "network-namespace", "systemd", "linux"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Internet :: Proxy Servers",
  "Topic :: System :: Networking"
]
dependencies = []

[project.urls]
Homepage = "https://github.com/Amir-A664/OpenStream/"
Repository = "https://github.com/Amir-A664/OpenStream/"
Issues = "https://github.com/Amir-A664/OpenStream/issues"

[project.scripts]
opst = "openstream.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
openstream = ["templates/*.tpl", "templates/systemd/*.tpl"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E501"]
